name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test_linux:
    name: Test on Linux with Node.js ${{matrix.node}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
          key: ${{runner.os}}-node-${{matrix.node}}-${{hashFiles('yarn.lock')}}
      - name: Install
        run: yarn
      - name: Run tests
        run: yarn test:all
