name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test_linux:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: borales/actions-yarn@v2.0.0
        with:
          name: Install
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          name: Test all
          cmd: test:all
