name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Deploy
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: deploy # will run `yarn deploy` command
