name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: GitHub Build & Deploy Action
        uses: jeoy/github-deploy-actions@v1.0.1
        env:
          COMMIT_EMAIL: mattia.richetto@gmail.com
          COMMIT_NAME: mattiaerre
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: main
          DEPLOY_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn build
          FOLDER: build
