name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        run: yarn install
      - name: Git config
        run: git config --global user.email "mattia.richetto@example.com"
        run: git config --global user.name "Mattia Richetto"
      - name: Deploy
        run: yarn deploy
